name: consentpvp
version: '1.0-SNAPSHOT'
main: org.modularsoft.consentpvp.ConsentPVP
author: "ModularSoft"
description: A plugin to manage PVP consent and combat in Minecraft.
commands:
  pvp:
    description: Manage your PVP consent and requests.
    usage: /pvp <enable|disable|request|accept>
    permission: consentpvp.use
    permission-message: You don't have permission to use this command.
permissions:
  consentpvp.use:
    description: Allows players to use the /pvp command.
    default: true
  consentpvp.admin:
    description: Allows admins to bypass cooldowns and combat restrictions.
    default: op